on: pull_request

jobs:
    example_comment_pr:
        runs-on: ubuntu-latest
        name: PR comment
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: "Comment PR"
              uses: actions/github-script@0.3.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const { issue: { number: issue_number }, repo: { owner, repo }, payload } = context;
                      console.log("payload", payload)
                      var prName = payload.pull_request.head.ref.match(/feature\/(.+)/)[1]
                      host = `${prName}.feature.shiftx.com`
                      const commitTime = ""
                      const version =  new Date(Date.parse(commitTime)).toISOString().substr(0, 19) + "Z"
                      github.issues.createComment({ issue_number, owner, repo, body: `Feature url: https://${host}` });
